"""Ed25519 audit trail signing — cryptographic tamper-proof event log."""

from __future__ import annotations

import base64
import os
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
)
from filelock import FileLock


def _default_key_path() -> Path:
    """Default signing key location: ``$XDG_CONFIG_HOME/mcp-firewall/mcp-firewall.key``.

    Falls back to ``~/.config/mcp-firewall/mcp-firewall.key``. An absolute,
    per-user path is used so the key does not end up in whichever project
    directory happens to be the current working directory.
    """
    config_home = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    return config_home / "mcp-firewall" / "mcp-firewall.key"


class AuditSigner:
    """Sign and verify audit log entries with Ed25519.

    The private key is stored unencrypted (PKCS8/PEM) and protected by
    filesystem permissions only (0600, owner read/write). Keep it out of
    version control (``mcp-firewall.key`` is gitignored by default).
    """

    def __init__(self, key_path: str | Path | None = None) -> None:
        self._key_path = Path(key_path) if key_path else _default_key_path()
        self._pub_path = self._key_path.with_suffix(".pub")
        self._private_key: Ed25519PrivateKey | None = None
        self._public_key: Ed25519PublicKey | None = None

        self._key_path.parent.mkdir(parents=True, exist_ok=True)
        # A shared default key must not be regenerated by simultaneous proxies.
        with FileLock(str(self._key_path) + ".lock"):
            if self._key_path.exists():
                self._load_keys()
            else:
                self._generate_keys()

    def _generate_keys(self) -> None:
        """Generate new Ed25519 keypair."""
        self._private_key = Ed25519PrivateKey.generate()
        self._public_key = self._private_key.public_key()

        # Save private key. The file is created with mode 0o600 via os.open so
        # there is no window between write_bytes() and chmod() where the key
        # would be readable under a permissive umask.
        pem = self._private_key.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, NoEncryption())
        self._key_path.parent.mkdir(parents=True, exist_ok=True)
        fd = os.open(self._key_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "wb") as f:
            f.write(pem)
        self._key_path.chmod(0o600)  # enforce 0o600 even if the file pre-existed

        # Save public key
        pub_pem = self._public_key.public_bytes(Encoding.PEM, PublicFormat.SubjectPublicKeyInfo)
        self._pub_path.write_bytes(pub_pem)

    def _load_keys(self) -> None:
        """Load existing keypair."""
        from cryptography.hazmat.primitives.serialization import load_pem_private_key

        pem = self._key_path.read_bytes()
        self._private_key = load_pem_private_key(pem, password=None)  # type: ignore
        self._public_key = self._private_key.public_key()  # type: ignore

    def sign(self, data: str) -> str:
        """Sign data, return base64-encoded signature."""
        if not self._private_key:
            raise RuntimeError("No signing key loaded")
        sig = self._private_key.sign(data.encode())
        return base64.b64encode(sig).decode()

    def verify(self, data: str, signature_b64: str) -> bool:
        """Verify a signature."""
        if not self._public_key:
            raise RuntimeError("No public key loaded")
        try:
            sig = base64.b64decode(signature_b64)
            self._public_key.verify(sig, data.encode())
            return True
        except Exception:
            return False

    @property
    def public_key_pem(self) -> str:
        """Get public key as PEM string."""
        if not self._public_key:
            return ""
        return self._public_key.public_bytes(
            Encoding.PEM, PublicFormat.SubjectPublicKeyInfo
        ).decode()


class AuditVerifier:
    """Verify entries with a trusted public key; never access a private key."""

    def __init__(self, public_key_path: str | Path | None = None) -> None:
        from cryptography.hazmat.primitives.serialization import load_pem_public_key

        path = Path(public_key_path) if public_key_path else _default_key_path().with_suffix(".pub")
        public_key = load_pem_public_key(path.read_bytes())
        if not isinstance(public_key, Ed25519PublicKey):
            raise ValueError("Audit public key must be Ed25519")
        self._public_key = public_key

    def verify(self, data: str, signature: str) -> bool:
        try:
            self._public_key.verify(base64.b64decode(signature, validate=True), data.encode())
            return True
        except (InvalidSignature, ValueError, TypeError):
            return False
